# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reflection_coefficient = QtWidgets.QPushButton(self.centralwidget)
        self.reflection_coefficient.setGeometry(QtCore.QRect(470, 90, 121, 61))
        self.reflection_coefficient.setObjectName("reflection_coefficient")
        self.transmission_coefficient = QtWidgets.QPushButton(self.centralwidget)
        self.transmission_coefficient.setGeometry(QtCore.QRect(340, 90, 121, 61))
        self.transmission_coefficient.setObjectName("transmission_coefficient")
        self.te_wave = QtWidgets.QPushButton(self.centralwidget)
        self.te_wave.setGeometry(QtCore.QRect(340, 20, 121, 61))
        self.te_wave.setObjectName("te_wave")
        self.tm_wave = QtWidgets.QPushButton(self.centralwidget)
        self.tm_wave.setGeometry(QtCore.QRect(470, 20, 121, 61))
        self.tm_wave.setObjectName("tm_wave")
        self.current_config = QtWidgets.QLabel(self.centralwidget)
        self.current_config.setGeometry(QtCore.QRect(610, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.current_config.setFont(font)
        self.current_config.setObjectName("current_config")
        self.config1 = QtWidgets.QLabel(self.centralwidget)
        self.config1.setGeometry(QtCore.QRect(610, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.config1.setFont(font)
        self.config1.setObjectName("config1")
        self.config2 = QtWidgets.QLabel(self.centralwidget)
        self.config2.setGeometry(QtCore.QRect(610, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.config2.setFont(font)
        self.config2.setObjectName("config2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 180, 421, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.figure_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.figure_layout.setContentsMargins(0, 0, 0, 0)
        self.figure_layout.setObjectName("figure_layout")
        self.level_number = QtWidgets.QLabel(self.centralwidget)
        self.level_number.setGeometry(QtCore.QRect(40, 60, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.level_number.setFont(font)
        self.level_number.setObjectName("level_number")
        self.frequency = QtWidgets.QLabel(self.centralwidget)
        self.frequency.setGeometry(QtCore.QRect(40, 110, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.frequency.setFont(font)
        self.frequency.setObjectName("frequency")
        self.frequency_2 = QtWidgets.QLabel(self.centralwidget)
        self.frequency_2.setGeometry(QtCore.QRect(10, 160, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.frequency_2.setFont(font)
        self.frequency_2.setObjectName("frequency_2")
        self.write_data = QtWidgets.QPushButton(self.centralwidget)
        self.write_data.setGeometry(QtCore.QRect(40, 330, 271, 61))
        self.write_data.setObjectName("write_data")
        self.surface_impedance = QtWidgets.QLabel(self.centralwidget)
        self.surface_impedance.setGeometry(QtCore.QRect(20, 390, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.surface_impedance.setFont(font)
        self.surface_impedance.setObjectName("surface_impedance")
        self.surface_impedance_2 = QtWidgets.QLabel(self.centralwidget)
        self.surface_impedance_2.setGeometry(QtCore.QRect(30, 440, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.surface_impedance_2.setFont(font)
        self.surface_impedance_2.setObjectName("surface_impedance_2")
        self.surface_impedance_3 = QtWidgets.QLabel(self.centralwidget)
        self.surface_impedance_3.setGeometry(QtCore.QRect(150, 440, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.surface_impedance_3.setFont(font)
        self.surface_impedance_3.setObjectName("surface_impedance_3")
        self.line_edit_level_number = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_level_number.setGeometry(QtCore.QRect(140, 70, 161, 41))
        self.line_edit_level_number.setObjectName("line_edit_level_number")
        self.line_edit_frequency = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_frequency.setGeometry(QtCore.QRect(140, 120, 161, 41))
        self.line_edit_frequency.setObjectName("line_edit_frequency")
        self.textEdit_medium_matrix = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_medium_matrix.setGeometry(QtCore.QRect(140, 180, 161, 111))
        self.textEdit_medium_matrix.setObjectName("textEdit_medium_matrix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reflection_coefficient.setText(_translate("MainWindow", "反射系数曲线"))
        self.transmission_coefficient.setText(_translate("MainWindow", "透射系数曲线"))
        self.te_wave.setText(_translate("MainWindow", "TE波"))
        self.tm_wave.setText(_translate("MainWindow", "TM波"))
        self.current_config.setText(_translate("MainWindow", "当前绘制图线："))
        self.config1.setText(_translate("MainWindow", "（请设置波形TE/TM）"))
        self.config2.setText(_translate("MainWindow", "（请设置绘制曲线类型）"))
        self.level_number.setText(_translate("MainWindow", "介质层数："))
        self.frequency.setText(_translate("MainWindow", "频率(Hz)："))
        self.frequency_2.setText(_translate("MainWindow", "电磁参数矩阵："))
        self.write_data.setText(_translate("MainWindow", "写入参数并计算"))
        self.surface_impedance.setText(_translate("MainWindow", "垂直入射表面阻抗："))
        self.surface_impedance_2.setText(_translate("MainWindow", "None"))
        self.surface_impedance_3.setText(_translate("MainWindow", "Ω"))

